### PR TITLE
TE-013 Order service and controller refactoring

### LINKED ISSUE #35: TE-013 Order service and controller refactoring
- [ ] reduce order controller so that it just passes request input to the service

- [ ] integrate mail service into order service logic

- [ ]  create more business exceptions

- [ ] create integration and unit tests for service and controller

- [ ] fix issues with ApplicationContext in other tests

### PR DESCRIPTION
**Pull request by lenagainulina**
Fixes #35
- refactored order controller and order service
- added business exceptions
- added integration test for order service
- added mvc unit test for order controller
- fixed problems with ApplicationContext in other tests
- made some minor adjustments

### CODE REVIEW

File: src/main/java/de/berlin/lostberlin/controller/BusinessController.java [hunk 1]
```diff
@@ -13,14 +14,15 @@
...
+    @Autowired
     private BusinessService businessService;
 
     public BusinessController(BusinessService businessService) {
         this.businessService = businessService;
     }
 
     @GetMapping
-    public ResponseEntity getBusinesses(@RequestParam (required=true, value = "location") String serviceLocation){
+    public ResponseEntity getBusinesses(@RequestParam(required = true, value = "location") String serviceLocation) {
```
Comment (sergeylukichev) [inline src/main/java/de/berlin/lostberlin/controller/BusinessController.java]: ResponseEntity  should be parametrised: ResponseEntity<Business>

File: src/main/java/de/berlin/lostberlin/service/OrderServiceImpl.java [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+        order.setDate(orderProfile.getDate());
+        order.setTime(orderProfile.getTime());
+        order.setParticipantsNr(orderProfile.getParticipantsNr());
+        order.setDescription(orderProfile.getDescription());
+        order.setStatus(StatusTypes.PENDING);
+        orderRepo.save(order);
+
+        Order result = order;
+
+        if (result != null) {
```
Comment (sergeylukichev) [inline src/main/java/de/berlin/lostberlin/service/OrderServiceImpl.java]: I think result is never null since you have created order with 'new' operator and then assigned result to this order.

File: src/main/java/de/berlin/lostberlin/service/mail/MailService.java [hunk 3]
```diff
@@ -28,39 +33,35 @@
...
         map.put("orderNumber", order.getOrderNr());
 
         return new Params(fromMail, toMail, subject, map);
     }
 
-    private Params createNotificationMailParams(Order order) {
-        Business business = null;
+    private Params createNotificationMailParams(OrderFullDao order) {
+        Business business;
         Optional result = businessRepo.findById(order.getBusinessId());
```
Comment (sergeylukichev) [inline src/main/java/de/berlin/lostberlin/service/mail/MailService.java]: Optional should be parametrised, i.e. Optional<Business>, the code below (Business)result.get() is nasty.

File: src/main/java/de/berlin/lostberlin/service/mail/MailService.java [hunk 4]
```diff
@@ -28,39 +33,35 @@
...
         map.put("name", order.getName());
         map.put("orderNumber", order.getOrderNr());
 
         return new Params(fromMail, toMail, subject, map);
     }
 
-    private Params createNotificationMailParams(Order order) {
-        Business business = null;
+    private Params createNotificationMailParams(OrderFullDao order) {
+        Business business;
```
Comment (sergeylukichev) [inline src/main/java/de/berlin/lostberlin/service/mail/MailService.java]: You actually do not need this declaration here. It is enough to declare it below when you first get its value.

File: src/main/java/de/berlin/lostberlin/service/mail/Params.java [hunk 5]
```diff
@@ -3,34 +3,34 @@
 import java.util.Map;
 
 public class Params {
-	
-	private String toMail;
```
Comment (sergeylukichev) [inline src/main/java/de/berlin/lostberlin/service/mail/Params.java]: So, what is finally here as padding? Tabs or spaces?

File: src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java [hunk 6]
```diff
@@ -9,106 +8,55 @@
...
-    ValidatorFactory factory;
-
-
     @Before
     public void setUp() {
-        businessService = new BusinessServiceImpl(businessRepository);
-
-        //factory = Validation.buildDefaultValidatorFactory();
+        businessService = new BusinessServiceImpl(businessRepo);
     }
```
Comment (sergeylukichev) [inline src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java]: If you create businessService here, you do not need to autowire it above.

File: src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java [hunk 7]
```diff
@@ -9,106 +8,55 @@
...
-/*
-Unfortunately, I get the same problem with @JpaAuditing annotation even after it's been externalized to ApplicationConfig file. So I had to comment it out for making tests.
-I added @ContextConfiguration because ApplicationContext could not be loaded without it.
- */
 
 @RunWith(SpringRunner.class)
-@ContextConfiguration(classes = ApplicationConfig.class, initializers = ConfigFileApplicationContextInitializer.class)
-@SpringBootTest
+@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
 public class BusinessServiceTest {
```
Comment (sergeylukichev) [inline src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java]: I still cannot make it work since it creates MailService beans as well (which we do not need for the test) and cannot find sendgrid.properties file.

Comment (sergeylukichev) [reply src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java]: Damn, seems to work, bloody stuff. See pr.

File: src/main/java/de/berlin/lostberlin/service/mail/Params.java (hunk 5 above)
Comment (lenagainulina) [reply src/main/java/de/berlin/lostberlin/service/mail/Params.java]: you mean formatting, right? I auto-formatted all code, so it should be 4 spaces. I hope I understood you correctly.

File: src/main/java/de/berlin/lostberlin/controller/BusinessController.java (hunk 1 above)
Comment (lenagainulina) [reply src/main/java/de/berlin/lostberlin/controller/BusinessController.java]: Yeah, I noticed that I forgot to do that right after I created PR and updated it right away (but you were still faster:)

File: src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java (hunk 7 above)
Comment (sergeylukichev) [reply src/test/java/de/berlin/lostberlin/service/BusinessServiceTest.java]: Just opened one

File: src/main/java/de/berlin/lostberlin/service/OrderServiceImpl.java (hunk 2 above)
Comment (lenagainulina) [reply src/main/java/de/berlin/lostberlin/service/OrderServiceImpl.java]: Right, I removed the condition completely.

File: src/main/java/de/berlin/lostberlin/service/mail/MailService.java (hunk 3 above)
Comment (lenagainulina) [reply src/main/java/de/berlin/lostberlin/service/mail/MailService.java]: fixed it
